package sop_corba;


/**
* sop_corba/AudioStreamPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from audio_stream.idl
* Monday, 27 February 2023 02:20:57 o'clock CET
*/

public abstract class AudioStreamPOA extends org.omg.PortableServer.Servant
 implements sop_corba.AudioStreamOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("obtenerAudio", new java.lang.Integer (0));
    _methods.put ("obtenerDuracion", new java.lang.Integer (1));
    _methods.put ("obtenerDuracionTotal", new java.lang.Integer (2));
    _methods.put ("obtenerNombre", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/AudioStream/obtenerAudio
       {
         byte $result[] = null;
         $result = this.obtenerAudio ();
         out = $rh.createReply();
         sop_corba.BufferHelper.write (out, $result);
         break;
       }


  //Obtener duracion actual del audio
       case 1:  // sop_corba/AudioStream/obtenerDuracion
       {
         int $result = (int)0;
         $result = this.obtenerDuracion ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  //Obtener duracion total del audio
       case 2:  // sop_corba/AudioStream/obtenerDuracionTotal
       {
         int $result = (int)0;
         $result = this.obtenerDuracionTotal ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  //Obtener el nombre del audio
       case 3:  // sop_corba/AudioStream/obtenerNombre
       {
         String $result = null;
         $result = this.obtenerNombre ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/AudioStream:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AudioStream _this() 
  {
    return AudioStreamHelper.narrow(
    super._this_object());
  }

  public AudioStream _this(org.omg.CORBA.ORB orb) 
  {
    return AudioStreamHelper.narrow(
    super._this_object(orb));
  }


} // class AudioStreamPOA
