package sop_corba;


/**
* sop_corba/AudioStreamIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./audio_stream.idl
* Monday, June 12, 2017 4:35:12 PM UTC
*/

public interface AudioStreamIntOperations 
{
  byte[] obtenerAudio ();
} // interface AudioStreamIntOperations
