package sop_corba;


/**
* sop_corba/AudioStreamIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./audio_stream.idl
* Monday, June 12, 2017 4:35:12 PM UTC
*/

public class AudioStreamIntPOATie extends AudioStreamIntPOA
{

  // Constructors

  public AudioStreamIntPOATie ( sop_corba.AudioStreamIntOperations delegate ) {
      this._impl = delegate;
  }
  public AudioStreamIntPOATie ( sop_corba.AudioStreamIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public sop_corba.AudioStreamIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (sop_corba.AudioStreamIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public byte[] obtenerAudio ()
  {
      System.out.println("llamando");
    return _impl.obtenerAudio();
  } // obtenerAudio

  private sop_corba.AudioStreamIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class AudioStreamIntPOATie
