package sop_corba;


/**
* sop_corba/AudioStream.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from audio_stream.idl
* lunes 12 de junio de 2017 10:40:30 PM UTC
*/

public interface AudioStream extends AudioStreamOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AudioStream
