package sop_corba;


/**
* sop_corba/AudioStreamInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./audio_stream.idl
* Monday, June 12, 2017 4:35:12 PM UTC
*/

public interface AudioStreamInt extends AudioStreamIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AudioStreamInt
